visualization: True #TODO:icluse this option in launch file
#all angles are in DEGREES
rope_length: 1.5
calculate_new_path: True

env_mesh: "env-scene-ltu-experiment-hole-inclined"

#Planning
val_check_resolution: 0.01
use_mesh_improvement: True
use_dynamic_goal: False

optimal_objective: "obstacle_clearance" #values:None, ob.PathLengthOptimizationObjective,balanced,obstacle_clearance

safety_distances: { drones: 0.1, lowest_point: 0.1 }

# start and goal
start: { x: -0.5, y: 3, z: 0.75 }
goal: { x: +0.5, y: 5, z: 0.75 }

# Bounds of states
bounds:
  {
    low: [-1.5, -2.8, 0.3, -180, 0.2, -60],
    high: [1.5, 5.0, 2.5, 180, 0.9, 60],
  }

#planner algorithm
planner_algorithm: "og.RRT"
